### ISSUE TITLE
Run arviz compatibility job in GitHub Actions

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4256]
xref this job which was run by TravisCI

```
jobs:
  include:
  - name: ArviZ compatibility
    stage: test
    install:
      - . ./scripts/create_testenv.sh
      - conda activate testenv
      # replace ArviZ with the latest master
      - pip install git+git://github.com/arviz-devs/arviz.git
      - pip install codecov
      - conda list && pip freeze
      - export FLOATX='float64'
    script:
      - . ./scripts/test.sh --durations=10 --cov-append pymc3/tests/test_sampling.py
    after_success: skip
```
