### ISSUE TITLE
Update Docker image to `v4`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5323]
As discussed in the meeting earlier today, it is now time to update the Docker image: https://hub.docker.com/u/pymc

# Short-term goals
* [x] Update the `Dockerfile` to a fresh base image (done in #5881)
* [ ] Create a GitHub Action to build & push the Docker image. (#5939)
* [x] Install dependencies to NOT get the `NumPy C-API` warning... (done in #5881)
* [x] Install graphviz/pydot such that `pm.model_to_graphviz()` doesn't raise errors. (done in #5881)
* (optional, b/c difficult) Install graphviz dependencies such that it can render to a file 👇

```python
with pymc.Model() as pmodel:
    pymc.Normal()
fp = pathlib.Path("model.pdf")
graph = pymc.model_to_graphviz(pmodel)
graph.render(format="pdf", filename=str(fp))
assert fp.exists()
```

# Simplifications/Constraints
* Python minor versions don't matter much these days, shall we build it for just `3.9` for now?
* We'll want a "latest" build and one per release? For `4.0.0b1` that'll be a manually built one, but for upcoming ones we can automate it?

Tagging @canyon289 @AustinRochford @bwengals who have relevant insight.

I can also contribute a (stripped-down) `environment.yml` to start from 👇

Known limitations:
* Suffers from `NumPy C-API` warning
* Graphviz/pydot install to the degree that `pm.model_to_graphviz()` doesn't raise, but rendering to fixes crashes.

```yaml
channels:
- defaults
- conda-forge
dependencies:
- conda-build
- libblas
- mkl-service
- numpy>=1.15.0
- pip
# To fix pydot/graphviz (?)
- pango
- pydot
# Limit graphviz upper version because of https://stackoverflow.com/a/69997168/4473230
- python-graphviz<=0.18
- scipy>=1.2.0
# To be discussed:
- jupyterlab
- statsmodels
- watermark
- pip:
  - matplotlib>=3.*
  - pandas>=1.*
  # PyMC installs more reliably with pip
  # as long as important dependencies are installed with conda already
  - git+https://github.com/pymc-devs/pymc@9d4691c4ceaa18dd50081db32f38fd1310359d48
  # To be discussed:
  - scikit-learn
  - openpyxl
```

When this issue is dealt with we can also close #3160 + #4386 as fixed and wontfix respectively.
