### ISSUE TITLE
Switch GitHub Actions to install environments with `mamba`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5375]
Our CI pipelines are taking quite a bit of compute time and **per job** already 3.5 minutes are just for creating the conda environments.

Switching to `mamba` could save quite a lot of compute time & energy there!

**Comment by michaelosthege** [comment]
When doing this, it'd be great to combine `pre-commit.yml`, `arviz_compat.yml` and `pytest.yml` into the same workflow.
Then we could fail-fast all jobs when the pre-commit doesn't pass (#5041)

**Comment by parthb83** [comment]
Hey @michaelosthege! I would like to work on this issue. Can you please guide me through the process of resolving this issue.

**Comment by michaelosthege** [comment]
> Hey @michaelosthege! I would like to work on this issue. Can you please guide me through the process of resolving this issue.

Most importantly these lines will need to be changed: https://github.com/pymc-devs/pymc/blob/main/.github/workflows/pytest.yml#L114-L140

Try to google for other example where GitHub actions are used with mamba. Maybe there are some equivalents to the cache & setup actions in the aforementioned lines.

**Comment by parthb83** [comment]
> Most importantly these lines will need to be changed: https://github.com/pymc-devs/pymc/blob/main/.github/workflows/pytest.yml#L114-L140
> Try to google for other example where GitHub actions are used with mamba. Maybe there are some equivalents to the cache & setup actions in the aforementioned lines.

```
- name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment-test-py37.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/environment-test-py37.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          use-mamba: true
          activate-environment: pymc-test-py37
          channel-priority: strict
          environment-file: conda-envs/environment-test-py37.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
```

Ok so I changed the code by adding 2 lines `mamba-version: "*"` and `use-mamba: true`. Do you think this is sufficient to create conda environment with `mamba`? If so, please tell a way to run this on github actions to validate the solution.
