### ISSUE TITLE
Add `no releasenotes` label to PRs by Autoupdate pre-commit config

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6139]
Is this possible? Config is here: https://github.com/pymc-devs/pymc/blob/main/.github/workflows/autoupdate-pre-commit-config.yml

**Comment by williambdean** [comment]
Can do this with :

```yaml
# .github/workflows/bot-prs.yml
name: Bot PRs

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  label-no-releasenotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Label no releasenotes
        run: |
          number=${{ github.event.pull_request.number }}
          is_bot=$(gh pr view $number --json author --jq '.author.is_bot')
          bot_login=$(gh pr view $number --json author --jq '.author.login')
          if [[ $is_bot == "true" && $bot_login != "copilot-swe-agent" ]]; then
            gh pr edit $number --add-label "no releasenotes"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
```

PyMC-Marketing : https://github.com/pymc-labs/pymc-marketing/blob/main/.github/workflows/bot-prs.yml
